<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../approveLargeOrder.wsdl"/>
      <rootElement name="Order" namespace="http://xmlns.oracle.com/ns/order"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../WriteApprovalResults.wsdl"/>
      <rootElement name="Order" namespace="http://xmlns.oracle.com/ns/order"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [SAT MAR 14 15:51:54 BRT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/POProcessing/POProcessing/WriteApprovalResults"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ns1="http://xmlns.oracle.com/ns/order"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:client="http://xmlns.oracle.com/POProcessing/POProcessing/approveLargeOrder"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plnk wsdl ns1 xsd client tns jca xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns1:Order>
      <ns1:customerId>
        <xsl:value-of select="/ns1:Order/ns1:customerId"/>
      </ns1:customerId>
      <ns1:orderId>
        <xsl:value-of select="/ns1:Order/ns1:orderId"/>
      </ns1:orderId>
      <xsl:if test="/ns1:Order/ns1:prodName">
        <ns1:prodName>
          <xsl:value-of select="/ns1:Order/ns1:prodName"/>
        </ns1:prodName>
      </xsl:if>
      <xsl:if test="/ns1:Order/ns1:itemType">
        <ns1:itemType>
          <xsl:value-of select="/ns1:Order/ns1:itemType"/>
        </ns1:itemType>
      </xsl:if>
      <xsl:if test="/ns1:Order/ns1:price">
        <ns1:price>
          <xsl:value-of select="/ns1:Order/ns1:price"/>
        </ns1:price>
      </xsl:if>
      <xsl:if test="/ns1:Order/ns1:qty">
        <ns1:qty>
          <xsl:value-of select="/ns1:Order/ns1:qty"/>
        </ns1:qty>
      </xsl:if>
      <xsl:if test="/ns1:Order/ns1:status">
        <ns1:status>
          <xsl:value-of select="/ns1:Order/ns1:status"/>
        </ns1:status>
      </xsl:if>
      <xsl:if test="/ns1:Order/ns1:creditCardInfo">
        <ns1:creditCardInfo>
          <ns1:cardNumber>
            <xsl:value-of select="/ns1:Order/ns1:creditCardInfo/ns1:cardNumber"/>
          </ns1:cardNumber>
          <ns1:cardType>
            <xsl:value-of select="/ns1:Order/ns1:creditCardInfo/ns1:cardType"/>
          </ns1:cardType>
        </ns1:creditCardInfo>
      </xsl:if>
    </ns1:Order>
  </xsl:template>
</xsl:stylesheet>
